---
# tasks file for rpi_network

- name: Set static IP with template
  ansible.builtin.template:
    src: dhcpcd.j2
    dest: /etc/dhcpcd.conf
    backup: true
    mode: "644"
  # Do not restart the dhcpcd service because we will lose connection
  # notify: Restart dhcpcd.service
  become: true


- name: Apt update and upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    cache_valid_time: 3600
  become: true


- name: Install packages (defined in vars)
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
  become: true


- name: Enable fail2ban
  ansible.builtin.service:
    name: fail2ban
    enabled: true
    state: started
  become: true


- name: Add additional fail2ban jails
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/fail2ban/jail.d/
    mode: "644"
  loop:
    - fail2ban_default.conf
    - fail2ban_sshd.conf
    - fail2ban_recidive.conf
  notify: Restart fail2ban
  become: true


- name: Show fail2ban status on ssh login
  ansible.builtin.copy:
    src: 50-fail2ban-status
    dest: /etc/update-motd.d/
    mode: "0755"
  become: true


- name: Remove uname and motd files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/motd
    - /etc/update-motd.d/10-uname
  become: true
  notify: Restart ssh
