---
# handlers file for rpi_network
- name: Restart dhcpcd.service
  ansible.builtin.service:
    name: dhcpcd.service
    state: restarted
  become: true


- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  become: true


- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
  become: true