---
# Start of the playbook / task

#installing samba
- name: install samba
  ansible.builtin.package:
    name: samba
    state: present

#Create a sambausers group, all users in this group will have read and write permissions in the share later
- name: create a sambausrs group 
  ansible.builtin.group:
    name: "{{ smb_group }}"
    state: present

#Create samba users 
- name: create a samba user
  ansible.builtin.user:
    name: "{{ item.smb_user }}"
    password: "{{ item.smb_password | password_hash('sha512')}}"
    groups: "{{ item.smb_group }}, sudo, sambashare"
    shell: /bin/bash
    state: present
  loop: "{{ users }}"


#ALLOW THE USERS TO ACTUALLY USE SAMBA (from windows machine)
#see https://stackoverflow.com/questions/44762488/non-interactive-samba-user-creation-via-ansible
- name: Configure Samba users.
  ansible.builtin.shell: >
    (pdbedit --user={{ item.smb_user }} 2>&1 > /dev/null)
    || (echo '{{ item.smb_password }}'; echo '{{ item.smb_password }}')
    | smbpasswd -s -a {{ item.smb_user }}
  register: smbpasswd
  changed_when: "'Added user' in smbpasswd.stdout"
  loop: "{{ users }}"



#The share location is default at /home/sambauser/share, this can be changed by changing the smb_path variable
- name: create a samba share directory
  ansible.builtin.file:
    path: "{{ smb_path }}"
    state: directory
    owner: "{{ smb_user }}" #since "sambauser" doesn't seem to work, I added the smb_user variable, which is "louis"
    group: "{{ smb_group }}"
    mode: 0777
    # mode: 0770

#Using the template module, the smb.conf file is created from the smb.conf.j2 file
#Afterwards, the samba service is restarted
- name: create a samba share in the config file
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    mode: 0644
    backup: yes
  notify: restart samba