---
# Start of the playbook / task

- name: install samba
  ansible.builtin.package:
    name: samba
    state: present

#create a sambausers group, all users in this group will have read and write permissions in the share later
- name: create a sambausrs group 
  ansible.builtin.group:
    name: "{{ smb_group }}"
    state: present

#create a samba user
- name: create a samba user
  ansible.builtin.user:
    name: "{{ smb_user }}"
    password: "{{ smb_password | password_hash('sha512')}}"
    groups: "{{ smb_group }}, sudo"
    shell: /bin/bash
    state: present

- name: create a samba share directory
  ansible.builtin.file:
    path: "{{ smb_path }}"
    state: directory
    owner: "{{ smb_user }}"
    group: "{{ smb_group }}"
    mode: 0770
  
- name: create a samba share in the config file
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    mode: 0644
    backup: yes
  notify: restart samba
